import React from "react";
import { SectionHeading } from "../../components/document/SectionHeading.jsx";
import { DocCard } from "../../components/document/DocCard.jsx";
import { DocHeader } from "../../components/document/DocHeader.jsx";
import { StepCard } from "../../components/document/StepCard.jsx";
import { AccentPanel } from "../../components/document/AccentPanel.jsx";
import { Callout } from "../../components/document/Callout.jsx";
import { QuoteBanner } from "../../components/document/QuoteBanner.jsx";
import { TermList } from "../../components/document/TermList.jsx";
import { InlineCode } from "../../components/document/InlineCode.jsx";
import { FeedbackBar } from "../../components/chrome/FeedbackBar.jsx";
import { DocFooter } from "../../components/chrome/DocFooter.jsx";

export function DocsArticle() {
  const [vote, setVote] = React.useState(null);
  return (
    <article className="td-doc" style={{ maxWidth: "var(--doc-measure)", margin: "0 auto", padding: "var(--space-8) var(--space-7) 0" }}>
      <DocHeader
        meta={["Product area", "Release name", "Updated month year"]}
        title="Feature name and what it does"
        standfirst="One or two sentences that say plainly what the capability does and why the reader is here. It carries considerations the reader should review before enabling it."
      />

      <SectionHeading level={2}>What You Need to Know</SectionHeading>
      <DocCard>
        <SectionHeading level={3}>First concept</SectionHeading>
        <p>
          Explain the behaviour in full sentences. State what the system does when the setting is enabled, and where the
          processing happens, without commentary.
        </p>
        <SectionHeading level={3}>Second concept</SectionHeading>
        <p style={{ marginBottom: 0 }}>
          Name the condition, then the consequence. Parenthetical examples are fine (e.g., a regional compliance
          requirement, or any restriction on where processing may occur).
        </p>
      </DocCard>

      <SectionHeading level={2}>Notification</SectionHeading>
      <p>Starting with the named release, an informational banner appears when one or more items use this capability:</p>
      <QuoteBanner label="Banner Message:">
        "Quote product copy exactly as the reader will see it in the interface, including any inline{" "}
        <a href="#">documentation link</a> and the bracketed action text at the end. [View affected items]"
      </QuoteBanner>
      <AccentPanel label="Banner Actions:">
        <TermList
          style={{ marginBottom: 0 }}
          items={[
            { term: "View affected items", text: "Click to see which items use the capability" },
            { term: "Show less", text: "Collapse the banner (it will reappear in future sessions)" },
          ]}
        />
      </AccentPanel>

      <SectionHeading level={2}>Action Required</SectionHeading>
      <p>Before enabling or continuing to use this capability, you must:</p>
      <StepCard number={1} title="Review Your Policies">
        <p><strong>Action:</strong> Confirm that the configuration aligns with your organization's governance and compliance standards.</p>
        <p style={{ marginBottom: "var(--space-2)" }}><strong>Key Questions:</strong></p>
        <TermList
          style={{ marginBottom: 0 }}
          items={[
            "Does your organization have requirements about where data is processed?",
            "Are there regulatory requirements that mandate data stay within specific boundaries?",
            "Does your privacy policy allow for processing outside your chosen location?",
          ]}
        />
      </StepCard>
      <StepCard number={2} title="Understand What Is Sent">
        <p style={{ marginBottom: "var(--space-2)" }}><strong>Sent to the service:</strong></p>
        <TermList items={["The request generated by the feature", "Context needed to complete the request"]} />
        <p style={{ marginBottom: "var(--space-2)" }}><strong>Not sent to the service:</strong></p>
        <AccentPanel style={{ marginBottom: 0 }}>
          <TermList
            style={{ marginBottom: 0 }}
            items={["Your records", "User credentials and authentication data", "Internal knowledge content", "Execution logs and history"]}
          />
        </AccentPanel>
      </StepCard>
      <AccentPanel variant="info" label="How the data is protected:">
        <TermList
          style={{ marginBottom: 0 }}
          items={[
            { term: "Encryption", text: "TLS 1.2 in transit" },
            { term: "Masking", text: "If configured, sensitive data is masked before leaving your environment" },
            { term: "Content filtering", text: "If configured, harmful content is detected and blocked" },
            { term: "Access Controls", text: "Permissions determine who can trigger the capability" },
          ]}
        />
      </AccentPanel>

      <SectionHeading level={2}>If This Conflicts with Your Policies</SectionHeading>
      <p>Alternative approaches:</p>
      <DocCard title="Option 1: Use an internal source">
        <TermList
          style={{ marginBottom: 0 }}
          items={["Configure the feature against your own internal content", "Confirm that content is comprehensive and current", "Keep all processing inside your environment"]}
        />
      </DocCard>
      <DocCard title="Option 2: Remove the capability from affected items">
        <AccentPanel style={{ marginBottom: 0 }}>
          <TermList
            ordered
            style={{ marginBottom: 0 }}
            items={[
              "Navigate to the administration area",
              "Open the item you want to change",
              <>Review the <InlineCode>Tools</InlineCode> section</>,
              "Find the capability in the assigned list and remove it",
              "Save the configuration",
              "Test the item to confirm it functions correctly without the capability",
            ]}
          />
        </AccentPanel>
      </DocCard>
      <Callout variant="caution">
        If the workflow depends on this capability, you may need to reconfigure its logic or provide alternative data
        sources.
      </Callout>

      <SectionHeading level={2}>Frequently Asked Questions</SectionHeading>
      <DocCard title="Why is processing handled this way?">
        <p>The capability relies on a third-party service offered under a global deployment model. This means:</p>
        <TermList
          style={{ marginBottom: 0 }}
          items={[
            "Requests are routed across the provider's global infrastructure",
            "Processing location is optimized by the provider for performance and availability",
            "The service is not region-locked",
            "This is a characteristic of the provider's service design, not a configuration choice",
          ]}
        />
      </DocCard>
      <DocCard title="What does the provider do with the data?">
        <TermList
          items={[
            "Your records and internal data are not sent (only the request and its context)",
            <>The provider does <strong>not</strong> use this data to train models</>,
            "Any retention window is solely for service operation and debugging",
          ]}
        />
        <p style={{ marginBottom: "var(--space-2)" }}><strong>For detailed information, review:</strong></p>
        <TermList
          style={{ marginBottom: 0 }}
          items={[
            <a href="#">The provider's privacy resource center</a>,
            <a href="#">Security controls documentation</a>,
            <a href="#">Data retention documentation</a>,
            <a href="#">Service-specific terms</a>,
            <a href="#">Data processing addendum</a>,
          ]}
        />
      </DocCard>
      <DocCard title="Can this be used in a compliant way?">
        <p>It depends on your specific requirements:</p>
        <AccentPanel variant="pass" label={<span style={{ color: "var(--td-green-700)", fontSize: "var(--size-h4)" }}>✓ Potentially Compliant If:</span>}>
          <TermList
            style={{ marginBottom: 0 }}
            items={[
              "Your policies allow for global processing with appropriate safeguards",
              "You've completed a risk assessment or impact assessment",
              "You've documented the necessity and business justification",
            ]}
          />
        </AccentPanel>
        <AccentPanel variant="fail" style={{ marginBottom: 0 }} label={<span style={{ color: "var(--td-red-700)", fontSize: "var(--size-h4)" }}>✗ Likely Not Compliant If:</span>}>
          <TermList
            style={{ marginBottom: 0 }}
            items={["Regulation mandates that data stay within a specific geography", "Your agreements prohibit onward transfers"]}
          />
        </AccentPanel>
      </DocCard>
      <DocCard title="Will a regional option be offered?">
        <p>Watch for updates:</p>
        <TermList
          style={{ marginBottom: 0 }}
          items={["Review quarterly release notes", "Subscribe to product documentation updates", "Engage with your account contact", "Provide feedback about your requirements"]}
        />
      </DocCard>
      <DocCard title="Can processing location be configured?">
        <p>No. The capability uses a global deployment, which means:</p>
        <TermList
          items={[
            "Processing location cannot be restricted to a specific region or country",
            "The provider determines routing based on their global infrastructure",
            "This is a characteristic of the provider's service, not configurable here",
          ]}
        />
        <p style={{ marginBottom: 0 }}>
          <strong>If this doesn't align with your policies:</strong> Use the alternative approaches listed above.
        </p>
      </DocCard>

      <FeedbackBar style={{ marginTop: "var(--space-9)" }} value={vote} onVote={setVote} />
      <DocFooter wordmark="[brand]" company="[Company]" />
    </article>
  );
}
